### ISSUE TITLE
Repostitory structure for 2021.3.0 is not compliant

### ISSUE THREAD

**Issue by agdamsbo** [ChristofferG/homeassistant-dmipollen#1]
Hi! I would like to use this repository, however, on import to HACS, I get the error: "Repostitory structure for 2021.3.0 is not compliant"
Can you help?

**Comment by ChristofferG** [comment]
Hi @agdamsbo, 
Where do you get this error? 
I have just tried to remove the repository and component from my HACS, restart HomeAssitant, add repository and install the component again without any issues.
I'm running  HomeAssistant v2021.5.2 and HACS v1.12.3.

**Comment by agdamsbo** [comment]
Aha. Just tried again after fresh restart after having tried several times. Everything works. Gosh. Thanks!
